# Generated by Django 3.2.3 on 2021-06-04 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterid', models.CharField(max_length=1)),
                ('semestername', models.CharField(max_length=20)),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asessionid', models.CharField(max_length=9)),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('asetid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=6)),
                ('coursename', models.CharField(max_length=30)),
                ('coursenature', models.CharField(max_length=1)),
                ('passmark', models.IntegerField()),
                ('courseunit', models.IntegerField()),
                ('courseGuId', models.UUIDField(default=uuid.uuid4)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.asemester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studentGuId', models.UUIDField(default=uuid.uuid4)),
                ('asession', models.CharField(max_length=9)),
                ('faculty', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=40)),
                ('programme', models.CharField(max_length=40)),
                ('applicationnumber', models.CharField(max_length=20)),
                ('formno', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('presentstate', models.CharField(max_length=20)),
                ('graduatingsession', models.CharField(max_length=9)),
                ('asetid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.aset')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='mscdocuments')),
                ('dateuploaded', models.DateField(default=datetime.datetime(2021, 6, 4, 12, 38, 7, 188554, tzinfo=utc), verbose_name='Payment Date')),
                ('thesessionofinterest', models.CharField(max_length=9)),
                ('description', models.CharField(default='', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='SessionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.asession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateregistered', models.DateField(default=datetime.datetime(2021, 6, 4, 12, 38, 7, 190291, tzinfo=utc), verbose_name='Registered Date')),
                ('status', models.CharField(max_length=20)),
                ('totalregisteredunit', models.SmallIntegerField()),
                ('maxpossibleunit', models.SmallIntegerField()),
                ('minpossibleunit', models.SmallIntegerField()),
                ('coursetoRegister', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='toregister', to='ResultApp.course')),
                ('registeredCourses', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alreadyregistered', to='ResultApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='DetailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('readonly', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('donedate', models.DateField(default=datetime.datetime(2021, 6, 4, 12, 38, 7, 192027, tzinfo=utc), verbose_name='Registered Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailaddress', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=40)),
                ('fieldofinterest', models.CharField(max_length=40)),
                ('contactaddress', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('localgovt', models.CharField(max_length=30)),
                ('modeofstudy', models.CharField(max_length=30)),
                ('nextofkinnames', models.CharField(max_length=50)),
                ('nextofkinaddress', models.CharField(max_length=50)),
                ('nextofkinphoneno', models.CharField(max_length=50)),
                ('nextofkinrelationship', models.CharField(max_length=50)),
                ('maritalstatus', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='asession',
            name='aset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.aset'),
        ),
        migrations.AddField(
            model_name='asemester',
            name='aset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.asession'),
        ),
    ]
