# Generated by Django 3.2.3 on 2021-06-08 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0002_auto_20210604_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='aset',
            name='MinimumCompulsoryUnit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aset',
            name='MinimumElectiveUnit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aset',
            name='MinimumGraduatingUnit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aset',
            name='MinimumRequiredUnit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursenature',
            field=models.CharField(choices=[('R', 'Required'), ('E', 'Elective'), ('R', 'Compulsory')], max_length=1),
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 20, 56, 17, 445916, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 20, 56, 17, 444194, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 20, 56, 17, 442385, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
