# Generated by Django 3.2.3 on 2021-06-24 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0003_auto_20210608_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courselevel',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseunit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='passmark',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 13, 8, 52, 484326, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 13, 8, 52, 482656, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 13, 8, 52, 480829, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
