# Generated by Django 3.2.3 on 2021-07-01 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0007_auto_20210626_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 16, 14, 52, 822977, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='coursetoRegister',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 16, 14, 52, 821369, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='registeredCourses',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 16, 14, 52, 819549, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
