# Generated by Django 3.2.3 on 2021-07-02 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0008_auto_20210701_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcourse',
            name='asession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.asession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 16, 37, 16, 984314, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 16, 37, 16, 982621, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 16, 37, 16, 980805, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
