# Generated by Django 3.2.3 on 2021-07-03 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0010_auto_20210703_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcourse',
            name='courseGuId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 7, 3, 15, 41, 1, 124585, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 7, 3, 15, 41, 1, 122881, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 7, 3, 15, 41, 1, 121048, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
