# Generated by Django 3.2.3 on 2021-07-03 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0011_auto_20210703_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredcourse',
            name='courseGuId',
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 7, 3, 15, 42, 5, 220962, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 7, 3, 15, 42, 5, 219234, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 7, 3, 15, 42, 5, 217416, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
