# Generated by Django 3.2.3 on 2021-07-05 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0012_auto_20210703_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 3, 41, 770321, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 3, 41, 768588, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='presentstate',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('GRADUATE', 'GRADUATE'), ('SUSPENDED', 'SUSPENDED'), ('LEAVE', 'LEAVE'), ('WITHDRAW', 'WITHDRAW'), ('ABSENT', 'ABSENT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 3, 41, 766808, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
