# Generated by Django 3.2.3 on 2021-07-09 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0015_auto_20210708_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='option',
            field=models.CharField(default='A', max_length=40),
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 14, 40, 17, 966764, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 14, 40, 17, 965106, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 14, 40, 17, 963291, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
