# Generated by Django 3.2.3 on 2021-07-13 22:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0017_auto_20210709_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asession',
            name='aset',
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 22, 38, 16, 820381, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 22, 38, 16, 818712, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 22, 38, 16, 816930, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
