# Generated by Django 3.2.3 on 2021-08-08 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0019_auto_20210717_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailresult',
            name='asemester',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='ResultApp.asemester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailresult',
            name='registeredDate',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 20, 33, 14, 76859, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 20, 33, 14, 76828, tzinfo=utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 20, 33, 14, 75070, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 20, 33, 14, 73247, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
