# Generated by Django 3.2.3 on 2021-08-08 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0020_auto_20210808_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 21, 14, 11, 709520, tzinfo=utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='registeredDate',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 21, 14, 11, 709567, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 21, 14, 11, 707812, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 21, 14, 11, 705960, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
