# Generated by Django 3.2.3 on 2021-08-08 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0021_auto_20210808_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailresult',
            name='donedate',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 21, 19, 38, 78918, tzinfo=utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='detailresult',
            name='registeredDate',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 21, 19, 38, 78950, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 21, 19, 38, 77206, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='dateuploaded',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 21, 19, 38, 75350, tzinfo=utc), verbose_name='Payment Date'),
        ),
    ]
